# 얼굴인식 도메인 모델 설정
# 버전: v1.0.0
# 최종 업데이트: 2025-06-28

# 기본 설정
default:
  detection_model: "ultraface_rfb_320"
  recognition_model: "arcface_resnet100"
  device: "auto"  # auto, cpu, cuda
  batch_size: 1
  
# 얼굴 검출 모델 설정
face_detection:
  # 기본 모델 (UltraFace RFB - 안정적이고 빠름)
  default_model: "ultraface_rfb_320"
  
  models:
    # UltraFace RFB-320 (초경량, 1MB)
    ultraface_rfb_320:
      model_path: "models/weights/face_detection_ultraface_rfb_320.onnx"
      framework: "onnx"
      input_size: [320, 240]
      confidence_threshold: 0.5
      nms_threshold: 0.4
      device: "auto"
      description: "UltraFace RFB-320 (안정적이고 빠름)"
      performance:
        gpu_inference_time_ms: 5
        cpu_inference_time_ms: 30
        memory_usage_mb: 64
    # SCRFD 고성능 모델 (buffalo_l)
    scrfd_10g:
      model_path: "models/weights/face_detection_scrfd_10g_20250628.onnx"
      framework: "onnx"
      input_size: [640, 640]
      confidence_threshold: 0.5
      nms_threshold: 0.4
      device: "auto"  # auto, cpu, cuda
      description: "SCRFD 얼굴 검출 모델 (10G FLOPS, 고성능)"
      performance:
        gpu_inference_time_ms: 15
        cpu_inference_time_ms: 120
        memory_usage_mb: 512
    
    # RetinaFace 경량 모델 (buffalo_s)
    retinaface_mnet025:
      model_path: "models/weights/face_detection_retinaface_mnet025_20250628.onnx"
      framework: "onnx"
      input_size: [640, 640]
      confidence_threshold: 0.5
      nms_threshold: 0.4
      device: "auto"
      description: "RetinaFace MobileNet0.25 (경량)"
      performance:
        gpu_inference_time_ms: 8
        cpu_inference_time_ms: 80
        memory_usage_mb: 256

    # RetinaFace ResNet50 모델 (고성능)
    retinaface_resnet50:
      model_path: "models/weights/face_detection_retinaface_resnet50.onnx"
      framework: "onnx"
      input_size: [640, 640]
      confidence_threshold: 0.5
      nms_threshold: 0.4
      device: "auto"
      description: "RetinaFace ResNet50 (고성능)"
      performance:
        gpu_inference_time_ms: 20
        cpu_inference_time_ms: 200
        memory_usage_mb: 512
    
    # OpenCV Haar Cascade (CPU 백업)
    opencv_haarcascade:
      model_path: "models/weights/face_detection_opencv_haarcascade_20250628.xml"
      framework: "opencv"
      scale_factor: 1.1
      min_neighbors: 3
      min_size: [30, 30]
      device: "cpu"
      description: "OpenCV Haar Cascade (CPU 전용 백업)"
      performance:
        cpu_inference_time_ms: 50
        memory_usage_mb: 64

# 얼굴 인식 모델 설정  
face_recognition:
  # 기본 모델 (GPU 최적화)
  default_model: "arcface_r100_buffalo_l"
  
  models:
    # ArcFace ResNet-100 (buffalo_l, 고성능)
    arcface_r100_buffalo_l:
      model_path: "models/weights/face_recognition_arcface_r100_20250628.onnx"
      framework: "onnx"
      input_size: [112, 112]
      embedding_size: 512
      device: "auto"
      description: "ArcFace ResNet-100 (buffalo_l, 고성능)"
      performance:
        gpu_inference_time_ms: 12
        cpu_inference_time_ms: 150
        memory_usage_mb: 1024
        accuracy_lfw: 0.9983
    
    # ArcFace ResNet-50 (buffalo_s, 균형)
    arcface_r50_buffalo_s:
      model_path: "models/weights/face_recognition_arcface_r50_20250628.onnx"
      framework: "onnx"
      input_size: [112, 112]
      embedding_size: 512
      device: "auto"
      description: "ArcFace ResNet-50 (buffalo_s, 균형)"
      performance:
        gpu_inference_time_ms: 8
        cpu_inference_time_ms: 100
        memory_usage_mb: 768
        accuracy_lfw: 0.9975
    
    # MobileFaceNet (초경량)
    mobilefacenet_buffalo_s:
      model_path: "models/weights/face_recognition_mobilefacenet_20250628.onnx"
      framework: "onnx"
      input_size: [112, 112]
      embedding_size: 128
      device: "auto"
      description: "MobileFaceNet (초경량)"
      performance:
        gpu_inference_time_ms: 3
        cpu_inference_time_ms: 25
        memory_usage_mb: 128
        accuracy_lfw: 0.9940

# 하드웨어별 최적화 설정
hardware_optimization:
  # GPU 환경 (고성능)
  gpu_high_performance:
    detection_model: "scrfd_10g"
    recognition_model: "arcface_r100_buffalo_l"
    batch_size: 4
    precision: "fp16"
    
  # GPU 환경 (균형)
  gpu_balanced:
    detection_model: "retinaface_mnet025"
    recognition_model: "arcface_r50_buffalo_s"
    batch_size: 2
    precision: "fp16"
    
  # CPU 환경 (경량)
  cpu_optimized:
    detection_model: "retinaface_mnet025"
    recognition_model: "mobilefacenet_buffalo_s"
    batch_size: 1
    precision: "fp32"
    
  # CPU 백업 (최소)
  cpu_fallback:
    detection_model: "opencv_haarcascade"
    recognition_model: "mobilefacenet_buffalo_s"
    batch_size: 1
    precision: "fp32"

# 성능 임계값 설정
performance_thresholds:
  detection:
    min_confidence: 0.5
    max_inference_time_ms: 100
    max_memory_usage_mb: 1024
    
  recognition:
    min_similarity: 0.6
    max_inference_time_ms: 150
    max_memory_usage_mb: 1024
    
  processing:
    max_batch_size: 8
    timeout_seconds: 30
    
# 품질 관리 설정
quality_control:
  face_quality:
    min_face_size: [80, 80]
    max_face_size: [640, 640]
    min_eye_distance: 30
    blur_threshold: 0.3
    
  embedding_quality:
    norm_threshold: [0.8, 1.2]
    consistency_check: true
    
  image_quality:
    min_resolution: [224, 224]
    max_file_size_mb: 10
    supported_formats: ["jpg", "jpeg", "png", "bmp"]
    
# 보안 설정
security:
  model_verification:
    check_file_integrity: true
    verify_model_signature: false  # 개발 환경에서는 비활성화
    
  privacy:
    anonymize_embeddings: true
    gdpr_compliance: true
    data_retention_days: 30
    face_data_anonymization: true
    encryption_enabled: true
    
  privacy_protection:
    blur_faces_in_logs: true
    secure_storage: true

# 데이터 증강 설정 (훈련 시 사용)
data_augmentation:
  enabled: true
  techniques:
    - horizontal_flip
    - brightness_adjustment
    - rotation
    - gaussian_noise
    
  parameters:
    brightness_range: [0.8, 1.2]
    rotation_range: [-15, 15]
    noise_variance: 0.01
    flip_probability: 0.5

# 로깅 및 모니터링 설정
monitoring:
  log_level: "INFO"
  performance_logging: true
  model_metrics: true
  
  metrics:
    - detection_accuracy
    - recognition_accuracy
    - processing_time
    - memory_usage
    - gpu_utilization

# 하드웨어별 최적화 설정
hardware_optimization:
  cpu:
    detection_model: "opencv_haarcascade"
    recognition_model: "mobilefacenet_buffalo_s"
    batch_size: 1
    num_threads: 4
    
  gpu:
    detection_model: "retinaface_resnet50"
    recognition_model: "arcface_resnet100"
    batch_size: 4
    precision: "fp16"
    
  jetson:
    detection_model: "retinaface_mobilenet"
    recognition_model: "facenet_inception"
    batch_size: 2
    tensorrt_optimization: true 