# 얼굴 품질평가 사용자 맞춤 설정
version: "1.0"
description: "사용자 정의 얼굴 품질평가 설정"

# 기본 임계값
quality_thresholds:
  min_face_size: 80          # 최소 얼굴 크기 (픽셀)
  blur_threshold: 100        # 블러 임계값 (높을수록 선명)
  brightness_min: 50         # 최소 밝기
  brightness_max: 200        # 최대 밝기
  contrast_min: 20           # 최소 대비

# 가중치 설정 (합계 = 1.0)
weights:
  size: 0.3                  # 크기 중요도 30%
  blur: 0.3                  # 선명도 중요도 30%
  brightness: 0.2            # 밝기 중요도 20%
  contrast: 0.2              # 대비 중요도 20%

# 품질 등급 기준
quality_grades:
  excellent: 0.8             # 우수 (80% 이상)
  good: 0.6                  # 양호 (60% 이상)
  fair: 0.4                  # 보통 (40% 이상)
  poor: 0.0                  # 불량 (40% 미만)

# 사용자 정의 품질평가 모드
custom_assessment:
  enable_face_angle: false   # 얼굴 각도 검사
  enable_eye_quality: false  # 눈 품질 검사  
  enable_mouth_quality: false # 입 품질 검사
  enable_symmetry: false     # 얼굴 대칭성 검사
  enable_age_filter: false   # 나이 필터
  enable_emotion_filter: false # 감정 필터

# 얼굴 각도 설정 (enable_face_angle: true 시)
face_angle_limits:
  max_yaw: 30               # 좌우 회전 최대 30도
  max_pitch: 20             # 위아래 회전 최대 20도
  max_roll: 15              # 기울기 최대 15도

# 눈 품질 설정 (enable_eye_quality: true 시)
eye_quality:
  min_eye_size: 10          # 최소 눈 크기
  require_both_eyes: true   # 양쪽 눈 모두 필요
  check_eye_openness: true  # 눈 뜸 상태 확인

# 나이 필터 설정 (enable_age_filter: true 시)
age_filter:
  min_age: 18              # 최소 나이
  max_age: 80              # 최대 나이

# 감정 필터 설정 (enable_emotion_filter: true 시)  
emotion_filter:
  allowed_emotions:        # 허용 감정
    - "neutral"            # 중립
    - "happy"              # 행복
  blocked_emotions:        # 차단 감정
    - "angry"              # 화남
    - "sad"                # 슬픔 