# 불량 검출 도메인 설정 파일
# 파일: config/defect_detection.yaml

version: "1.0.0"
meta:
  description: "불량 검출 도메인 설정"
  lastModified: "2025-01-28T10:00:00Z"
  status: "active"

# 모델 설정
models:
  defect_detection:
    path: "models/weights/defect_detection_yolov8n_factory_20250628.onnx"
    architecture: "yolov8n"
    input_size: [640, 640]
    confidence_threshold: 0.5
    nms_threshold: 0.4
    device: "auto"  # auto, cpu, cuda
    precision: "auto"  # auto, fp32, fp16

# 불량 유형 정의
defect_types:
  scratch:
    id: 0
    name: "스크래치"
    color: [0, 0, 255]  # BGR
    threshold: 0.3
    severity: "medium"
  
  dent:
    id: 1
    name: "찌그러짐"
    color: [0, 255, 0]  # BGR
    threshold: 0.4
    severity: "high"
  
  crack:
    id: 2
    name: "균열"
    color: [255, 0, 0]  # BGR
    threshold: 0.5
    severity: "critical"
  
  discoloration:
    id: 3
    name: "변색"
    color: [255, 255, 0]  # BGR
    threshold: 0.3
    severity: "low"

# 전처리 설정
preprocessing:
  resize: [640, 640]
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  augmentation:
    enabled: false
    brightness_range: [0.8, 1.2]
    contrast_range: [0.8, 1.2]

# 검출 설정
detection:
  min_defect_size: 20
  max_defect_size: 640
  enable_tracking: false
  enable_counting: true
  roi_enabled: false
  roi_coordinates: [0, 0, 640, 640]

# 품질 관리 설정
quality_control:
  alert_threshold: 0.05  # 5% 불량률에서 경고
  critical_threshold: 0.1  # 10% 불량률에서 심각 알림
  sampling_rate: 1.0  # 100% 샘플링
  auto_stop: false
  stop_threshold: 0.2  # 20% 불량률에서 자동 정지

# 성능 설정
performance:
  batch_size: 1
  num_threads: 4
  enable_cache: true
  cache_size: 100
  enable_optimization: true
  fps_target: 30

# 데이터베이스 설정
database:
  path: "data/domains/factory/defect_database.json"
  auto_save: true
  backup_enabled: true
  retention_days: 90

# 로깅 설정
logging:
  level: "INFO"
  file: "data/logs/defect_detection.log"
  max_size: "10MB"
  backup_count: 5

# 알림 설정
notifications:
  email_enabled: false
  email_recipients: []
  slack_enabled: false
  slack_webhook: ""
  alert_cooldown_minutes: 30

# 시각화 설정
visualization:
  show_confidence: true
  show_class_names: true
  show_timestamps: true
  save_images: true
  save_path: "data/output/defect_detection"
  image_format: "jpg"
  quality: 95

# 하드웨어 설정
hardware:
  gpu_memory_fraction: 0.8
  cpu_affinity: "auto"
  enable_tensorrt: false
  enable_openvino: false 